### PR TITLE
Tf 2.8.2 cpu gpu

### PR DESCRIPTION
**Pull request by tobijk**
This is a follow-up to https://github.com/AnacondaRecipes/tensorflow_recipes/pull/38. It consolidates all Windows and Linux CPU and GPU builds into a single recipe. The differences were too insignificant to warrant those being split out into different recipes and build scripts.

This won't build in Prefect, packages are built manually.

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
I am curious to know how the consolidation of the `tensorflow` recipes into a single recipe might affect the complexity of building `tensorflow`.

**Comment by tobijk** [comment]
If at all, it makes things easier. You can still use cbc.yaml to control which variants you want to build/don't build. Keeping different recipies for different variant just means that they potentially drift away from each other. You need to keep the build scripts in sync, etc. In case of the Windows builds, for example, the "vile hack" that makes sure libraries are linked and not just loaded at runtime was present in the GPU variant but missing from the CPU variant.

**Review by pseudoyim — APPROVED** [review]
👍 Thank you, Tobi!

**Comment by tobijk** [comment]
This has been up for a week for review. I'm merging this.

**Pull request merged**
